# Generated by Django 5.1 on 2024-08-23 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_rpmsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rpmsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
