# Generated by Django 5.1 on 2024-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_alter_dispatch_username_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='added',
        ),
        migrations.AddField(
            model_name='company',
            name='phonenum',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
