# Generated by Django 5.1 on 2024-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_loads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecasted_demand', models.FloatField()),
            ],
        ),
    ]
