# Generated by Django 5.1 on 2024-08-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_kpiclusterresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalrate', models.FloatField()),
                ('allmiles', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.loads')),
            ],
        ),
    ]
